name: Deployement

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Copy Files
      run: rsync -a /root/actions-runner-dc/_work/dc-new/dc-new/ /var/www/dc-new/
      
    - name: Install Depencdencies
      run: npm install --prefix /var/www/dc-new
    
    - name: Give Permission
      run: chmod -R 775 /var/www/dc-new/


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test